### NERD DOS DADOS - Comandos úteis para tratar dados

In [1]:
# Importando o pacote pandas
import pandas as pd

In [2]:
# Carregando os dados e armazenando em um DataFrame
df_notas = pd.read_excel('notas.xlsx')

In [3]:
# Visualizando o DataFrame
df_notas

    ID  DISCIPLINA   NT
0    1  Matematica  5.0
1    2  Matematica  7.0
2    3  Matematica  8.0
3    4  Matematica  9.0
4    5  Matematica  5.0
5    6  Matematica  7.0
6    7  Matematica  8.0
7    8  Matematica  9.0
8    9  Matematica  4.0
9   10  Matematica  5.0
10  10  Matematica  5.0
11   1  Matematica  6.0
12   2  Matematica  7.0
13   3  Matematica  6.0
14   4  Matematica  7.0
15   5  Matematica  NaN
16   6  Matematica  NaN
17   7  Matematica  8.0
18   8  Matematica  9.0
19   9  Matematica  5.0
20  10  Matematica  4.0

In [4]:
# Renomeia as variaveis
df_notas.rename(columns = {'ID':'ID_ALUNO','DISCIPLINA':'MATERIA','NT':'NOTAS'}, inplace = True)

In [5]:
# Visualizando o DataFrame com as colunas renomeadas
df_notas

    ID_ALUNO     MATERIA  NOTAS
0          1  Matematica    5.0
1          2  Matematica    7.0
2          3  Matematica    8.0
3          4  Matematica    9.0
4          5  Matematica    5.0
5          6  Matematica    7.0
6          7  Matematica    8.0
7          8  Matematica    9.0
8          9  Matematica    4.0
9         10  Matematica    5.0
10        10  Matematica    5.0
11         1  Matematica    6.0
12         2  Matematica    7.0
13         3  Matematica    6.0
14         4  Matematica    7.0
15         5  Matematica    NaN
16         6  Matematica    NaN
17         7  Matematica    8.0
18         8  Matematica    9.0
19         9  Matematica    5.0
20        10  Matematica    4.0

In [6]:
# Vamos descartar os valores duplicados
df_notas.drop_duplicates(['ID_ALUNO','MATERIA','NOTAS'], inplace = True)

In [7]:
# Visualizando o DataFrame após excluir os valores duplicados
df_notas

    ID_ALUNO     MATERIA  NOTAS
0          1  Matematica    5.0
1          2  Matematica    7.0
2          3  Matematica    8.0
3          4  Matematica    9.0
4          5  Matematica    5.0
5          6  Matematica    7.0
6          7  Matematica    8.0
7          8  Matematica    9.0
8          9  Matematica    4.0
9         10  Matematica    5.0
11         1  Matematica    6.0
13         3  Matematica    6.0
14         4  Matematica    7.0
15         5  Matematica    NaN
16         6  Matematica    NaN
19         9  Matematica    5.0
20        10  Matematica    4.0

In [8]:
# Visualizando a mediana dos dados
df_notas['NOTAS'].median()

6.0

In [9]:
# Preenchendo valores com a mediana dos dados
df_notas['NOTAS'] = df_notas['NOTAS'].fillna((df_notas['NOTAS'].median()))

In [10]:
df_notas

    ID_ALUNO     MATERIA  NOTAS
0          1  Matematica    5.0
1          2  Matematica    7.0
2          3  Matematica    8.0
3          4  Matematica    9.0
4          5  Matematica    5.0
5          6  Matematica    7.0
6          7  Matematica    8.0
7          8  Matematica    9.0
8          9  Matematica    4.0
9         10  Matematica    5.0
11         1  Matematica    6.0
13         3  Matematica    6.0
14         4  Matematica    7.0
15         5  Matematica    6.0
16         6  Matematica    6.0
19         9  Matematica    5.0
20        10  Matematica    4.0

In [11]:
# Preenchendo valores com a média dos dados
# Carregando o arquivo
df_notas = pd.read_excel('notas.xlsx')
df_notas.rename(columns = {'ID':'ID_ALUNO','DISCIPLINA':'MATERIA','NT':'NOTAS'}, inplace = True)
df_notas.drop_duplicates(['ID_ALUNO','MATERIA','NOTAS'], inplace = True)

In [12]:
# Visualizando a média dos dados
df_notas['NOTAS'].mean()

6.333333333333333

In [13]:
# Preenchendo valores com a média dos dados
df_notas['NOTAS'] = df_notas['NOTAS'].fillna((df_notas['NOTAS'].mean()))
df_notas

    ID_ALUNO     MATERIA     NOTAS
0          1  Matematica  5.000000
1          2  Matematica  7.000000
2          3  Matematica  8.000000
3          4  Matematica  9.000000
4          5  Matematica  5.000000
5          6  Matematica  7.000000
6          7  Matematica  8.000000
7          8  Matematica  9.000000
8          9  Matematica  4.000000
9         10  Matematica  5.000000
11         1  Matematica  6.000000
13         3  Matematica  6.000000
14         4  Matematica  7.000000
15         5  Matematica  6.333333
16         6  Matematica  6.333333
19         9  Matematica  5.000000
20        10  Matematica  4.000000

In [14]:
# Preenchendo valores nulos com zero
# Carregando o arquivo
df_notas = pd.read_excel('notas.xlsx')
df_notas.rename(columns = {'ID':'ID_ALUNO','DISCIPLINA':'MATERIA','NT':'NOTAS'}, inplace = True)
df_notas.drop_duplicates(['ID_ALUNO','MATERIA','NOTAS'], inplace = True)
df_notas

    ID_ALUNO     MATERIA  NOTAS
0          1  Matematica    5.0
1          2  Matematica    7.0
2          3  Matematica    8.0
3          4  Matematica    9.0
4          5  Matematica    5.0
5          6  Matematica    7.0
6          7  Matematica    8.0
7          8  Matematica    9.0
8          9  Matematica    4.0
9         10  Matematica    5.0
11         1  Matematica    6.0
13         3  Matematica    6.0
14         4  Matematica    7.0
15         5  Matematica    NaN
16         6  Matematica    NaN
19         9  Matematica    5.0
20        10  Matematica    4.0

In [15]:
# Preenchendo valores com valor zero
df_notas['NOTAS'] = df_notas['NOTAS'].fillna(0)
df_notas

    ID_ALUNO     MATERIA  NOTAS
0          1  Matematica    5.0
1          2  Matematica    7.0
2          3  Matematica    8.0
3          4  Matematica    9.0
4          5  Matematica    5.0
5          6  Matematica    7.0
6          7  Matematica    8.0
7          8  Matematica    9.0
8          9  Matematica    4.0
9         10  Matematica    5.0
11         1  Matematica    6.0
13         3  Matematica    6.0
14         4  Matematica    7.0
15         5  Matematica    0.0
16         6  Matematica    0.0
19         9  Matematica    5.0
20        10  Matematica    4.0